Flask homework
Oksana-robota/Studying pull request #20
Opened 2023-04-10 16:09 UTC by Oksana-robota

2023-04-10 17:34 UTC, Oksana-robota commented
Homework is in commit called "hw31"

2023-04-14 15:36 UTC, klymenok requested changes

2023-04-14 15:36 UTC, klymenok commented on HW31+/flask_app/views.py
> +@app.route('/users1')
Вам потрібно було замінити існуючі ендпоінти, а не створювати нові. Суть полягає у тому, що ви спочатку повертаєте захардкожені дані, а на цьому етапі замінюєете їх на дані, що містяться в базі даних

2023-04-14 15:36 UTC, klymenok commented on HW31+/flask_app/views.py
> +        return dict_users[:int(request.args.get('size'))]
Обмеження краще зробити на рівні запиту в базу даних, а не тут. Якщо у вас в базі буде 1000000 записів, а показати треба буде лише 10, то не дуже ефективно буде отримувати всі, щоб показати тільки 10 із них.
```
users_query = User.query.limit(int(request.args.get('size'))) if request.args.get('size') else User.query
all_users = users_query.all()

2023-04-14 15:36 UTC, klymenok commented on HW31+/flask_app/views.py
> +        return dict_users[:int(request.args.get('size'))]
Це ж стосується і подібних вибірок в інших ендпоінтах

2023-04-14 15:36 UTC, klymenok commented on HW31+/flask_app/views.py
> +    all_users = User.query.all()
Для отримання одного обʼєкта не потрібно фільтрувати їх в коді python. Можна отримати одразу один обʼєкт:
`user = User.query.get(user_id)`

2023-04-14 15:36 UTC, klymenok commented on HW31+/flask_app/views.py
> +    all_users = User.query.all()
Це ж стосується і подібних вибірок в інших ендпоінтах

2023-04-14 15:36 UTC, klymenok commented on HW31+/flask_app/views.py
> +            'first_name': user1[0].first_name,
У вас між purchase та іншими таблицями є звʼязок і ви можете його використовувати для доступу до атрибутів повʼязаних обʼєктів:
```
purchase.user.first_name
purchase.book.title
```

2023-04-14 15:36 UTC, klymenok commented on HW31+/flask_app/views.py
> +    all_books = Book.query.all()
Обʼєкти book та user можна отримати способом, який я описав вище:
`user = User.query.get(request.json.get('user_id')`

2023-04-14 15:36 UTC, klymenok commented on HW31+/flask_app/views.py
> +                'first_name': user1[0].first_name,
У вас між purchase та іншими таблицями є звʼязок і ви можете його використовувати для доступу до атрибутів повʼязаних обʼєктів:
```
purchase.user.first_name
purchase.book.title
```

2023-04-17 14:40 UTC, Oksana-robota commented on HW31+/flask_app/views.py
> +    all_users = User.query.all()
Done

2023-04-17 14:45 UTC, Oksana-robota commented on HW31+/flask_app/views.py
> +            'first_name': user1[0].first_name,
Спасибо, сразу не поняла как єто сделать))

2023-04-17 14:50 UTC, Oksana-robota commented on HW31+/flask_app/views.py
> +    all_books = Book.query.all()
Done

2023-04-17 14:50 UTC, Oksana-robota commented on HW31+/flask_app/views.py
> +                'first_name': user1[0].first_name,
Done

2023-04-17 14:55 UTC, Oksana-robota commented on HW31+/flask_app/views.py
> +@app.route('/users1')
Я поняла. В условиях ДЗ Веб-розробка за допомогою Flask. Part 3
в 5м задании было сказано следующее:
5. Модифікувати існуючі, або додати нові енпоінти. Дані відображати у форматі JSON або використовуючи HTML template

Я приняла решения оставить старые и создать новые, чтобы потом повторять информацию по всем ендпоинтам и не хотелось бы убирать старые. Можно ли оставить с новыми ендпоинтами?

2023-04-17 19:54 UTC, klymenok approved these changes
Looks good!

2023-04-17 20:07 UTC, merged