Django
Oksana-robota/Studying pull request #21
Opened 2023-04-12 16:01 UTC by Oksana-robota

2023-04-14 17:52 UTC, klymenok requested changes
PR містить зміни по Flask, а ДЗ по темі Django

2023-04-17 14:28 UTC, Oksana-robota commented
hw38 - в єтом коммите Джанго, посмотрите, пожалуйста)
Фласк удалила из этой директории

2023-04-17 19:53 UTC, klymenok requested changes

2023-04-17 19:53 UTC, klymenok commented on HW38+/django_project/settings.py
> +SECRET_KEY = 'django-insecure-u9ak5y)p(urornh%d3h^qj=c2o#9xe))obj-c6c#t18v4#+!o_'
перемістіть SECRET_KEY в .env

2023-04-17 20:13 UTC, Oksana-robota commented on HW38+/django_project/settings.py
> +SECRET_KEY = 'django-insecure-u9ak5y)p(urornh%d3h^qj=c2o#9xe))obj-c6c#t18v4#+!o_'
Done

2023-04-17 20:59 UTC, klymenok approved these changes
Looks good!

2023-04-18 08:37 UTC, merged