tests_django
Oksana-robota/Studying pull request #30
Opened 2023-05-24 11:00 UTC by Oksana-robota

2023-05-28 16:55 UTC, klymenok requested changes
Відсутнє виконання завдання 1

2023-05-28 16:55 UTC, klymenok commented on HW38+/user/tests.py
> +        print(self.user)
Зайві print можна видалити

2023-05-29 07:09 UTC, Oksana-robota commented
Сделала, до пул реквеста не добавились изначально)

2023-05-31 16:27 UTC, klymenok approved these changes
Looks good!

2023-05-31 16:57 UTC, merged