HW7
Oksana-robota/Studying pull request #5
Opened 2022-12-21 20:08 UTC by Oksana-robota

2022-12-26 20:43 UTC, klymenok requested changes

2022-12-26 20:43 UTC, klymenok commented on HW7/Homework_7.py
> +            del phone_book[name]
It is better to check if key exists before attempt to delete it

2022-12-26 20:43 UTC, klymenok commented on HW7/Homework_7.py
> +            print(f'Here you could see the info for "{name}": {phone_book[name]}')
It is better to check if key exists before attempt to access it

2022-12-27 17:37 UTC, Oksana-robota commented
Could you please check the homework for the 9th lecture. I'm not sure about the second task. So that, I provided to options (a and b). Option a I did on my own, the way I was thinking and my understanding of the iterators. Option b I googled classes for better understanding of them and did it using classes' examples. I would be glad if you comment the second task anyway. Thank you!

2022-12-27 20:02 UTC, klymenok requested changes

2022-12-27 20:02 UTC, klymenok commented on HW9/Homework_9.py
> +# 1. Fibonacci sequences using generator
This code shouldn't be here

2023-01-04 21:40 UTC, klymenok approved these changes
Looks good!

2023-01-05 06:42 UTC, merged